Repository 349Team/portal-aulas-online-frontend, pull requests merged in 2023-06, with the labels that each got.

#126 Concluir curso e baixar certificado
  src/pages/CourseDetails/course_details.css
  src/pages/CourseDetails/course_details.jsx
  src/pages/StudentLessonPage/api.js
Labels: Frontend, Aluno

#129 Adicionar seção nas aulas e ordena las usando drag and drop
  package-lock.json
  package.json
  src/api/category.js
  src/api/default.js
  src/pages/CreateLesson/index.jsx
  src/pages/CreateLesson/style.css
  src/pages/EditCategoryPage/index.js
  src/pages/EditCategoryPage/sortable-item-styles.css
  src/pages/EditCategoryPage/sortable-item.js
  src/pages/EditCategoryPage/styles.css
  src/pages/EditCourse/index.jsx
  src/pages/EditCourse/style.css
  src/pages/EditLesson/index.jsx
  src/routes/index.jsx
  yarn.lock
Labels: Enhancement, Frontend, Professor

#131 Adicionar ordenação drag and drop aulas e correção pagina detalhes
  src/api/category.js
  src/pages/CourseDetails/course_details.css
  src/pages/CourseDetails/course_details.jsx
  src/pages/CreateLesson/index.jsx
  src/pages/EditCategoryLessonOrder/index.js
  src/pages/EditCategoryLessonOrder/sortable-item-styles.css
  src/pages/EditCategoryLessonOrder/sortable-item.js
  src/pages/EditCategoryLessonOrder/styles.css
  src/pages/EditCategoryPage/index.js
  src/pages/EditCourse/index.jsx
  src/pages/EditCourse/style.css
  src/pages/EditLesson/index.jsx
  src/routes/index.jsx
Labels: Enhancement, Frontend, Professor

#133 122 f fazer anotações
  src/api/admin.js
  src/api/default.js
  src/components/NavBar/index.jsx
  src/components/Note/CardAnotation.jsx
  src/components/Note/style.css
  src/pages/AdminPageTeachers/index.jsx
  src/pages/AdminPageTeachers/style.css
  src/pages/NotesPage/index.jsx
  src/pages/NotesPage/style.css
  src/pages/StudentLessonPage/index.js
  src/routes/index.jsx
  yarn.lock
Labels: Enhancement, Administrador, Frontend, Aluno

#138 Corrigido problema da edição de perfil
  src/components/CardProfessorProfile/card_professor_profile.jsx
  src/pages/UserProfile/index.jsx
  yarn.lock
Labels: Bug, Frontend, Usuário
