Repository 349Team/portal-aulas-online-frontend, pull requests merged in 2023-05, with the labels that each got.

#81 65 f editar perfil
  src/pages/Register/index.jsx
  src/pages/UserProfile/index.jsx
  yarn.lock
Labels: enhancement, Frontend

#85 72 f fazer upload de foto de perfil
  src/api/auth-api.js
  src/api/default.js
  src/contexts/AuthContext.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/index.jsx
  src/pages/RecoverPassword/index.jsx
  src/pages/RecoverPassword/style.css
  src/pages/UserProfile/index.jsx
  src/routes/index.jsx
Labels: enhancement, Frontend

#86 83 ajustar listagens
  src/api/default.js
  src/pages/Home/Home.jsx
  src/pages/ProfessorCourses/index.jsx
  src/pages/StudentCourses/student_courses.jsx
  yarn.lock
Labels: bug, Frontend

#89 Adicionadas funcionalidades relacionadas a troca de senha.
  package-lock.json
  src/pages/ChangePassword/index.jsx
  src/pages/ChangePassword/style.css
  src/pages/Home/Home.jsx
  src/pages/RecoverPassword/index.jsx
  src/pages/Register/index.jsx
  src/pages/UserProfile/index.jsx
  src/pages/UserProfile/style.css
  src/routes/index.jsx
  yarn.lock
Labels: enhancement, Frontend

#92 67 f ver listagem de cursos favoritos
  src/components/NavBar/index.jsx
  src/pages/BookmarksPage/bookmark_page.css
  src/pages/BookmarksPage/bookmark_page.jsx
  src/pages/CourseDetails/course_details.css
  src/pages/CourseDetails/course_details.jsx
  src/pages/Register/index.jsx
  src/routes/index.jsx
  yarn.lock
Labels: enhancement, Frontend, usuário

#95 Feita a substituição dos alerts.
  package-lock.json
  package.json
  src/index.js
  src/pages/ChangePassword/index.jsx
  src/pages/CourseDetails/course_details.jsx
  src/pages/Login/index.jsx
  src/pages/Register/index.jsx
  yarn.lock
Labels: Enhancement, Frontend

#98 96 f ajusta funções de requisição
  src/api/admin.js
  src/api/auth-api.js
  src/api/password.js
  src/api/profile.js
  src/pages/AdminPage/index.jsx
  src/pages/ChangePassword/index.jsx
  src/pages/RecoverPassword/index.jsx
  src/pages/Register/index.jsx
  src/pages/UserProfile/index.jsx
Labels: Frontend, Ajuste

#100 99 f resolver os warnings de quando roda npm start
  src/api/admin.js
  src/api/auth-api.js
  src/api/default.js
  src/api/password.js
  src/components/AccordionList/accordion_list.jsx
  src/components/CardDetails/card_details.jsx
  src/components/NavBar/index.jsx
  src/contexts/AuthContext.jsx
  src/contexts/StrictRoute.jsx
  src/pages/AdminPage/index.jsx
  src/pages/BookmarksPage/bookmark_page.jsx
  src/pages/ChangePassword/index.jsx
  src/pages/CourseDetails/course_details.jsx
  src/pages/Home/Home.jsx
  src/pages/ProfessorCourses/index.jsx
  src/pages/StudentCourses/student_courses.jsx
  src/pages/StudentLessonPage/index.js
  yarn.lock
Labels: Frontend, Ajuste

#103 Concluir aula
  src/assets/no-image.png
  src/components/CardCourses/index.jsx
  src/pages/AdminPage/style.css
  src/pages/CourseDetails/course_details.css
  src/pages/CourseDetails/course_details.jsx
  src/pages/CreateCourse/style.css
  src/pages/CreateLesson/style.css
  src/pages/EditCourse/style.css
  src/pages/EditLesson/index.jsx
  src/pages/EditLesson/style.css
  src/pages/ProfessorCourses/index.jsx
  src/pages/StudentLessonPage/api.js
  src/pages/StudentLessonPage/index.js
  src/pages/StudentLessonPage/styles.css
  src/pages/UserProfile/index.jsx
Labels: Frontend, Aluno, Ajuste

#107 102 f corrigir mensagens de erro
  src/api/auth-api.js
  src/api/bookmark.js
  src/api/profile.js
  src/components/CardDetails/card_details.jsx
  src/pages/CourseDetails/course_details.jsx
  src/pages/EditCourse/index.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/index.jsx
  src/pages/ProfessorProfile/professor_profile.jsx
  src/pages/RecoverPassword/index.jsx
  src/pages/Register/index.jsx
  src/pages/UserProfile/index.jsx
Labels: Frontend, Ajuste

#109 #108 - Implementando search
  src/pages/Home/Home.jsx
  src/pages/Home/style.css
Labels: Enhancement, Frontend
